name:           AchieveCoin Project
description:    a truly decentralized cryptocurrency
nickname:       AchieveCoin
plugin_version: 2.2.0
#baseurl:        https://achievecoin.org
highlight:      true
future:         false #do not show post-dated posts
markdown:       kramdown
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - strikethrough
    - superscript
collections:
  examples:
    output: true
exclude:
  - node_modules/
