# basic options
title: AchieveCoin Project
author: argos pam
email: argosp@achievecoin.org
description: a truly decentralized cryptocurrency
twitter_username: AchieveCoin
github_username: AchieveCoin

github:
  repository_url: https://github.com/achievecoin/AchieveCoin
  mac_url: https://github.com/achievecoin/achievecoin.org/releases/pre-alpha/mac/bitcoin-qt
  win_url: https://github.com/achievecoin/achievecoin.org/releases/pre-alpha/win/bitcoin-qt.exe
  #lin_url:

show_downloads: true

# Build settings
theme: jekyll-theme-cayman
