# basic options
title: AchieveCoin Project
author: argos pam
email: argosp@achievecoin.org
description: a truly decentralized cryptocurrency
twitter_username: AchieveCoin
github_username: AchieveCoin

github:
  repository_url: https://github.com/achievecoin/AchieveCoin
  release_url: https://github.com/achievecoin/AchieveCoin/releases/latest

show_downloads: true

# Build settings
theme: jekyll-theme-cayman
