# basic options
title: ⨺ AchieveCoin Project
author: argos pam
email: argosp@achievecoin.org
description: a truly decentralized cryptocurrency
twitter_username: AchieveCoin
github_username: AchieveCoin

# Build settings
theme: jekyll-theme-cayman
