name:           AchieveCoin Project
description:    a truly decentralized cryptocurrency
nickname:       AchieveCoin
plugin_version: 2.2.0
baseurl:        http://achievecoin.org
highlight:      true
markdown:       redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - strikethrough
    - superscript
collections:
  examples:
    output: true
exclude:
  - node_modules/

theme: jekyll-theme-cayman
